### ISSUE TITLE
Application Not Responding - com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService, InvisibleToUser

### ISSUE THREAD

**Issue by w3b-amit** [CleverTap/clevertap-android-sdk#158]
Hello Team,
We are getting some ANRs from CleverTap SDK, please check it and resolve it ASAP.
Here are the logs we received from AppStore - 
**executing service ******.app/com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService, InvisibleToUser**
_com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService,_
```
at android.content.Intent.getAction (Intent.java:6763)
  at com.squareup.picasso.Dispatcher$NetworkBroadcastReceiver.onReceive (Dispatcher.java:562)
  at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52851 (LoadedApk.java:1322)
  at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7 (unavailable)
  at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run (unavailable)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6626)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)
```

**Comment by darshanclevertap** [comment]
Which version of the CleverTap Android SDK are you using?
Also, are these the entire logs?

**Comment by darshanclevertap** [comment]
Also can you share the devices affected?

**Comment by w3b-amit** [comment]
CleverTap SDK Version - 4.0.4
Yes, there is some more thread, around 30.
Device Affected - Motorola Moto G (5S) Plus - Android 8.1

**Comment by darshanclevertap** [comment]
Can you share the entire logs with us? If it's too long to be put as a comment, you can share a text file as well.
Also is this happening only for one device or multiple devices?

**Comment by w3b-amit** [comment]
Hi,
It happens to one device only. The logs are too long. I will attach all the thread log.

**Comment by darshanclevertap** [comment]
@w3b-amit You can copy all the logs to a text file and Github now allows you to upload files. So please upload them here.
Thanks!

**Comment by darshanclevertap** [comment]
@w3b-amit Are you still facing this ANR? If yes, can you share the entire ANR stack trace with us in a text file or Google Doc link?

**Comment by w3b-amit** [comment]
Hi @darshanclevertap, Sorry for late reply.
Yes, I am facing some ANRs. I am sharing all of them with you.
Most of them are coming at the time of launch when we register firebase and CleverTap.
I would like to share my approach of implementation, if anything I am doing wrong please let me know.

We have overridden the MultiDexApplication class named - AppController which implements ActivityLifecycleCallbacks.
onCreate() method - 

- We first register the Activity life cycle callbacks.
- Next, we initialise Firebase SDK - FirebaseApp.initializeApp(this);
- Next, we go for cleverTap initialisation like this
             CleverTapAPI clevertapDefaultInstance = CleverTapAPI.getDefaultInstance(getApplicationContext());
             CleverTapAPI.getDefaultInstance(getApplicationContext()).enableDeviceNetworkInfoReporting(true);
- Next, we setup branch with cleverTap identifier like this
            Branch.getAutoInstance(application_context);
            Branch.getAutoInstance(application_context).setRequestMetadata("$clevertap_attribution_id", CleverTapAPI.getDefaultInstance(getApplicationContext()).getCleverTapAttributionIdentifier());

All these codes work on the main thread synchornusly.
Please look into my implementation steps if I am doing anything wrong, let me know.

I am attaching ANRs screen shots with expanded logs.

Thank you
![screencapture-play-google-console-u-1-developers-6052428917985423198-app-4973719351566878076-vitals-crashes-e38269f7-details-2021-05-03-20_43_40](https://user-images.githubusercontent.com/28981682/116895103-7a0d8680-ac50-11eb-959f-7b0436f7b8a8.png)
![screencapture-play-google-console-u-1-developers-6052428917985423198-app-4973719351566878076-vitals-crashes-14ca9b58-details-2021-05-03-20_40_14](https://user-images.githubusercontent.com/28981682/116895136-80036780-ac50-11eb-8f82-21d0101ba1ac.png)
![screencapture-play-google-console-u-1-developers-6052428917985423198-app-4973719351566878076-vitals-crashes-477b1906-details-2021-05-03-20_38_23](https://user-images.githubusercontent.com/28981682/116895144-81cd2b00-ac50-11eb-8dbd-70b22076a35b.png)

**Comment by darshanclevertap** [comment]
@w3b-amit 
Sorry for the delay in reply. We've been receiving many issues regarding ANRs, some have been legit, which some have been apps trying to load multiple SDKs at the start of the application. However, we've done an internal code review to find legit issues and two of the three ANRs faced by you are a part of the legit issues found by us.

Your logs had 3 main ANRs which I will list below and then give an explanation for the cause of all of them (which I understand from the logs shared)

1. Broadcast of Intent - `FirebaseInstanceIdReceiver`

Here the ANR is being caused by the `PusAmpResponse` class which is loading our `DBAdapter` class on the main thread. This is a legit issue and we're working on fixing this right away.

2. `SystemAlarmService`

Here the ANR is being caused by `setLastVisitTime` method which reads data from Shared Preferences. Usually, this should not be an issue on high-end devices, but we're working on fixing this on our end.

3. `CTBackgroundJobService`

Here there is no mention of CleverTap in the logs. `CTBackgroundJobService` is used for Push Amplification to ensure a higher delivery rate for Push Campaigns sent via CleverTap. As per the logs, I can see that some `ActivityThread` is trying to start when the `CTBackgroundJobService` runs and then a third party library `com.kbeanie.multipicker.utils.AMPFileProvider` tries to access the storage causing the ANR. If you could ensure this library doesn't initialize in the Application class, then this ANR can be avoided.

For issues 1 and 2, we'll fix the issues and release them in our next version, which is slated for release at the end of June. If you cannot wait till then, you can downgrade to v4.0.4 of our SDK. 

I hope this helps.

**Comment by naveenchandan** [comment]
@darshanclevertap any update on this issue?, we are also getting same anr

**Comment by darshanclevertap** [comment]
@w3b-amit Hey, sorry for the delay, the first 2 ANRs of "Broadcast of Intent" and "SystemAlarmService" have been fixed in [v4.2.0](https://github.com/CleverTap/clevertap-android-sdk/releases/tag/core-v4.2.0) of the CleverTap Android SDK. The 3rd one is not being caused by the CleverTap SDK as mentioned above.

@naveenchandan Can you go through my previous reply and let us know which ANR is affecting your app?

**Comment by w3b-amit** [comment]
Thank you,
I have updated the SDK.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
25/08/21,
12:46:04

**Comment by naveenchandan** [comment]
@darshanclevertap I'm getting the first ANR **FirebaseInstanceIdReceiver**, anyway I will update the sdk to v4.2.0 and revert back here

**Comment by naveenchandan** [comment]
other than this I'm getting two more ANRs from sdk
![Screenshot 2021-08-25 at 14 12 52](https://user-images.githubusercontent.com/23548335/130759354-01a0b713-58c4-4008-a255-dbc7d26b9024.png)
![Screenshot 2021-08-25 at 14 13 23](https://user-images.githubusercontent.com/23548335/130759422-7037033c-d949-49f1-a2f5-a16e663c91b9.png)

**Comment by naveenchandan** [comment]
@darshanclevertap any update on the ANR?, it's still occurring in latest version

**Comment by darshanclevertap** [comment]
@naveenchandan Can you share the logs for both `CTLocationUpdateReceiver` and the `XMPushService` ANR?

Also, can you let us know if you're using the CleverTap Xiaomi Push SDK (and the version), or have you integrated the Xiaomi Push SDK separately?

**Comment by darshanclevertap** [comment]
Closing this due to inactivity. Feel free to reopen.

**Comment by sachinsingh15** [comment]
@darshanclevertap Please find the details

CleverTap Android SDK : 4.4.0
CleverTap Geofence SDK: 1.0.2
CleverTap Xiaomi Push SDK : 1.0.2

**Comment by nikunjflobiz** [comment]
@darshanclevertap Getting below 
<img width="1261" alt="Screenshot 2022-10-18 at 9 22 58 AM" src="https://user-images.githubusercontent.com/86401784/196332134-b1d8229c-e22b-41a4-a406-0a02b10cda90.png">
ANR

We initialize CleverTap SDK instance in the Application onCreate() method,  Using CT SDK version:` 4.4.0`

**Comment by root-ansh-ct** [comment]
@nikunjflobiz are you able to replicate this?
The ANR seems to come during the system call to get notification channel. Will suggest to update the dependencies for CleverTap's Core SDK(4.6.4), XPS(1.5.1) and/or HMS(1.3.1)  to their latest version. Let me know if it resolves the issue
